apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: tomcat-container
        #image: 18.116.23.238:8083/springapp:${VERSION}
        image: 18.116.23.238:8083/springapp:13
        ports:
        - containerPort: 80

        
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
  labels:
    app: test-nodeport
spec:
  selector:
    app: nginx-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
